### PR TITLE
Improvised

### PR DESCRIPTION
**Pull request by ghost**
- Change the type to a pointer
- Remove unnecessary methods
- Less memory usage (slightly)

### CODE REVIEW

**Comment by rumblefrog** [comment]
Where's the ptr type change? Is this missing commits?

**Comment by ghost** [comment]
No. I've shortened and optimized the code to the best possible way so that it'll use a low usage of the user's memory.

**Comment by rumblefrog** [comment]
> Change the type to a pointer

But what type was changed to a pointer? And what's the motivation/rationale for the DBL struct? The PR description is superficial in the least.

**Comment by ghost** [comment]
The DBL Struct is added to easily manage the functions of the widget.

It can be also be reusable, if you want to. What I meant on "type to pointer" is that the BotID Str has been converted into a function that can be easily managed.

**Comment by ghost** [comment]
I made all of this so that this function is more complex and efficient when using it.

**Comment by rumblefrog** [comment]
Words like complex and efficient mean nothing if you have rational data to back them up, especially over a straightforward field type that occupies a few bytes.

Also, BotID interface method was removed, yet you implement them in your DBL receiver fn, so any method that accepts that interface would not be able to use that method.

**Comment by ghost** [comment]
Alright. Here's the most specific explanation for this commit:

I have changed the code to make it more readable and easier to understand.

I have also added a new function called `SetValue` which allows you to set a value for a key.

**Comment by rumblefrog** [comment]
Breaking code for more "efficient" and somehow more "readable" by adding more LOC, and an additional useless struct, when it's supposed to be extended by large and small structs, makes this a LQ PR.

**Pull request closed without merging**
